### PR TITLE
Solution to issue #34 in Python 2.7

### PR DESCRIPTION
**Pull request by Himanshu1495**

### CODE REVIEW

**Comment by msach22** [comment]
@Himanshu1495 please make sure to have 1 solution and test per merge request.

please fix and squash your commits

**Comment by Himanshu1495** [comment]
@msach22 , can you please elaborate "squashing the commits"? How to do that?

**Comment by ColinX13** [comment]
@Himanshu1495 because you have multiple solutions and tests for two questions on one branch you will need to put them on separate branches. 

1. check your repository with `git remote -v` to see if you have the repository for llipio. If not, you can add it by doing `git remote add llip https://github.com/llipio`. My remote is called llip so I'll use that as an example.
1. you need to download the code from the remote repository into your computer: `git fetch llip`.
1. change to a branch that doesn't have changes that you made so you can start clean:  `git checkout llip/master`.
1. create a new branch from there, I'll use h1 as an example `git checkout h1`.
1. add your changes. My example will be solutions/1.js: `git add solutions/1.js`
1. create a new commit by `git commit -m 'message'` 
1. make a pull request by `git push origin h1`.

Now, lets say if you want to solve another problem. Here's what you do:
1. change to a branch that doesn't have changes that you made so you can start clean:  `git checkout llip/master`.
1. create a new branch from there, I'll use h2 as an example `git checkout h2`.
...

Good luck!

**Comment by songz** [comment]
@ColinX13 great response, it was so good I added it to the wiki: https://github.com/llipio/algorithms/wiki/Git-and-branching

**Comment by Himanshu1495** [comment]
@ColinX13,@songz, should I close this pull request and start a new one?

**Comment by songz** [comment]
yes @Himanshu1495 , thank you. I'll close this PR

**Pull request closed without merging**
